In [25]:
#Question 1
#Load the csv file of the dataset into a dataframe in Python program.
import pandas as pd
#load dataframe from csv
#df = pd.read_csv(data_url)
data_url='https://raw.githubusercontent.com/fivethirtyeight/data/master/us-weather-history/KCLT.csv'
df = pd.read_csv(data_url)
#print dataframe
print(df)

          date  actual_mean_temp  actual_min_temp  actual_max_temp  \
0     2014-7-1                81               70               91
1     2014-7-2                85               74               95
2     2014-7-3                82               71               93
3     2014-7-4                75               64               86
4     2014-7-5                72               60               84
..         ...               ...              ...              ...
360  2015-6-26                85               70              100
361  2015-6-27                82               71               92
362  2015-6-28                76               66               85
363  2015-6-29                73               59               87
364  2015-6-30                83               71               94

     average_min_temp  average_max_temp  record_min_temp  record_max_temp  \
0                  67                89               56              104
1                  68                89               56              101
2                  68                89               56               99
3                  68                89               55               99
4                  68                89               57              100
..                ...               ...              ...              ...
360                67                88               55              102
361                67                88               56              103
362                67                88               53              101
363                67                88               54              104
364                67                89               54              104

     record_min_temp_year  record_max_temp_year  actual_precipitation  \
0                    1919                  2012                  0.00
1                    2008                  1931                  0.00
2                    2010                  1931                  0.14
3                    1933                  1955                  0.00
4                    1967                  1954                  0.00
..                    ...                   ...                   ...
360                  1979                  1952                  1.21
361                  2012                  1954                  0.55
362                  1968                  1959                  0.00
363                  1974                  2012                  0.00
364                  1962                  2012                  0.00

     average_precipitation  record_precipitation
0                     0.10                  5.91
1                     0.10                  1.53
2                     0.11                  2.50
3                     0.10                  2.63
4                     0.10                  1.65
..                     ...                   ...
360                   0.11                  1.98
361                   0.11                  1.86
362                   0.11                  1.83
363                   0.11                  2.39
364                   0.11                  2.75

[365 rows x 13 columns]

In [26]:
#Question 2
#Find the mean, median, mode, min and max for all numeric attributes.
numeric_ColumnDf=df[["actual_mean_temp","actual_min_temp","actual_max_temp","average_min_temp","average_max_temp","record_min_temp","record_max_temp","actual_precipitation","average_precipitation","record_precipitation"]].copy()
print(numeric_ColumnDf)
print("\n----------- Calculate Mean -----------\n")
print(numeric_ColumnDf.mean())
 
print("\n----------- Calculate Median -----------\n")
print(numeric_ColumnDf.median())
 
print("\n----------- Calculate Mode -----------\n")
print(numeric_ColumnDf.mode())

     actual_mean_temp  actual_min_temp  actual_max_temp  average_min_temp  \
0                  81               70               91                67
1                  85               74               95                68
2                  82               71               93                68
3                  75               64               86                68
4                  72               60               84                68
..                ...              ...              ...               ...
360                85               70              100                67
361                82               71               92                67
362                76               66               85                67
363                73               59               87                67
364                83               71               94                67

     average_max_temp  record_min_temp  record_max_temp  actual_precipitation  \
0                  89               56              104                  0.00
1                  89               56              101                  0.00
2                  89               56               99                  0.14
3                  89               55               99                  0.00
4                  89               57              100                  0.00
..                ...              ...              ...                   ...
360                88               55              102                  1.21
361                88               56              103                  0.55
362                88               53              101                  0.00
363                88               54              104                  0.00
364                89               54              104                  0.00

     average_precipitation  record_precipitation
0                     0.10                  5.91
1                     0.10                  1.53
2                     0.11                  2.50
3                     0.10                  2.63
4                     0.10                  1.65
..                     ...                   ...
360                   0.11                  1.98
361                   0.11                  1.86
362                   0.11                  1.83
363                   0.11                  2.39
364                   0.11                  2.75

[365 rows x 10 columns]

----------- Calculate Mean -----------

actual_mean_temp         61.049315
actual_min_temp          49.958904
actual_max_temp          71.630137
average_min_temp         48.819178
average_max_temp         70.983562
record_min_temp          31.465753
record_max_temp          88.728767
actual_precipitation      0.102411
average_precipitation     0.114082
record_precipitation      2.208904
dtype: float64

----------- Calculate Median -----------

actual_mean_temp         63.00
actual_min_temp          52.00
actual_max_temp          73.00
average_min_temp         48.00
average_max_temp         72.00
record_min_temp          30.00
record_max_temp          90.00
actual_precipitation      0.00
average_precipitation     0.11
record_precipitation      1.98
dtype: float64

----------- Calculate Mode -----------

   actual_mean_temp  actual_min_temp  actual_max_temp  average_min_temp  \
0              78.0             67.0               84              68.0
1               NaN              NaN               86               NaN
2               NaN              NaN               90               NaN

   average_max_temp  record_min_temp  record_max_temp  actual_precipitation  \
0              89.0             53.0            100.0                   0.0
1               NaN             55.0              NaN                   NaN
2               NaN              NaN              NaN                   NaN

   average_precipitation  record_precipitation
0                   0.11                  1.65
1                    NaN                  1.78
2                    NaN                  1.82

In [27]:
#Question 3
#Print the top 20% of rows showing only the first four columns.
n=len(df)*0.2
df.iloc[:, : 4].head(int(n))

         date  actual_mean_temp  actual_min_temp  actual_max_temp
0    2014-7-1                81               70               91
1    2014-7-2                85               74               95
2    2014-7-3                82               71               93
3    2014-7-4                75               64               86
4    2014-7-5                72               60               84
..        ...               ...              ...              ...
68   2014-9-7                79               70               88
69   2014-9-8                70               67               73
70   2014-9-9                72               66               77
71  2014-9-10                72               65               79
72  2014-9-11                77               64               89

[73 rows x 4 columns]

In [28]:
#Question 4
#Create a new column (call it ‘newColumn’), it should have the same values as the column‘actual_mean_temp’. Print head of dataframe.
df['newColumn'] = df['actual_mean_temp']
df.head()

,date,actual_mean_temp,actual_min_temp,actual_max_temp,average_min_temp,average_max_temp,record_min_temp,record_max_temp,record_min_temp_year,record_max_temp_year,actual_precipitation,average_precipitation,record_precipitation,newColumn
0,2014-7-1,81,70,91,67,89,56,104,1919,2012,0.00,0.10,5.91,81
1,2014-7-2,85,74,95,68,89,56,101,2008,1931,0.00,0.10,1.53,85
2,2014-7-3,82,71,93,68,89,56,99,2010,1931,0.14,0.11,2.50,82
3,2014-7-4,75,64,86,68,89,55,99,1933,1955,0.00,0.10,2.63,75
4,2014-7-5,72,60,84,68,89,57,100,1967,1954,0.00,0.10,1.65,72

In [29]:
#question 5
#Remove the new column that you have created above. Print head of dataframe.
del df['newColumn']
df.head()

,date,actual_mean_temp,actual_min_temp,actual_max_temp,average_min_temp,average_max_temp,record_min_temp,record_max_temp,record_min_temp_year,record_max_temp_year,actual_precipitation,average_precipitation,record_precipitation
0,2014-7-1,81,70,91,67,89,56,104,1919,2012,0.00,0.10,5.91
1,2014-7-2,85,74,95,68,89,56,101,2008,1931,0.00,0.10,1.53
2,2014-7-3,82,71,93,68,89,56,99,2010,1931,0.14,0.11,2.50
3,2014-7-4,75,64,86,68,89,55,99,1933,1955,0.00,0.10,2.63
4,2014-7-5,72,60,84,68,89,57,100,1967,1954,0.00,0.10,1.65

In [30]:
#Question 6
#Print the first 10 rows....save row containing data of ‘2014-7-3’  in a variable of type series (data structure)
print(df.iloc[0:10])
ser = df.loc[df['date'] == '2014-7-3']
print("The row with date 2014-7-3 is: ")
print(ser)
df = df[df.date != '2014-7-3']
print(df.iloc[0:10])

        date  actual_mean_temp  actual_min_temp  actual_max_temp  \
0   2014-7-1                81               70               91
1   2014-7-2                85               74               95
2   2014-7-3                82               71               93
3   2014-7-4                75               64               86
4   2014-7-5                72               60               84
5   2014-7-6                74               61               87
6   2014-7-7                79               67               91
7   2014-7-8                83               72               94
8   2014-7-9                80               71               89
9  2014-7-10                78               71               85

   average_min_temp  average_max_temp  record_min_temp  record_max_temp  \
0                67                89               56              104
1                68                89               56              101
2                68                89               56               99
3                68                89               55               99
4                68                89               57              100
5                68                89               57               99
6                68                89               55              100
7                68                89               58              101
8                68                89               57              101
9                68                89               53              101

   record_min_temp_year  record_max_temp_year  actual_precipitation  \
0                  1919                  2012                  0.00
1                  2008                  1931                  0.00
2                  2010                  1931                  0.14
3                  1933                  1955                  0.00
4                  1967                  1954                  0.00
5                  1964                  1948                  0.00
6                  1972                  1954                  0.00
7                  1892                  2010                  0.00
8                  1891                  1986                  0.15
9                  1961                  1926                  0.00

   average_precipitation  record_precipitation
0                   0.10                  5.91
1                   0.10                  1.53
2                   0.11                  2.50
3                   0.10                  2.63
4                   0.10                  1.65
5                   0.10                  1.95
6                   0.11                  2.37
7                   0.11                  1.87
8                   0.12                  3.71
9                   0.11                  2.45
The row with date 2014-7-3 is:
       date  actual_mean_temp  actual_min_temp  actual_max_temp  \
2  2014-7-3                82               71               93

   average_min_temp  average_max_temp  record_min_temp  record_max_temp  \
2                68                89               56               99

   record_min_temp_year  record_max_temp_year  actual_precipitation  \
2                  2010                  1931                  0.14

   average_precipitation  record_precipitation
2                   0.11                   2.5
         date  actual_mean_temp  actual_min_temp  actual_max_temp  \
0    2014-7-1                81               70               91
1    2014-7-2                85               74               95
3    2014-7-4                75               64               86
4    2014-7-5                72               60               84
5    2014-7-6                74               61               87
6    2014-7-7                79               67               91
7    2014-7-8                83               72               94
8    2014-7-9                80               71               89
9   2014-7-10                78               71               85
10  2014-7-11                78               68               87

    average_min_temp  average_max_temp  record_min_temp  record_max_temp  \
0                 67                89               56              104
1                 68                89               56              101
3                 68                89               55               99
4                 68                89               57              100
5                 68                89               57               99
6                 68                89               55              100
7                 68                89               58              101
8                 68                89               57              101
9                 68                89               53              101
10                68                89               55              100

    record_min_temp_year  record_max_temp_year  actual_precipitation  \
0                   1919                  2012                  0.00
1                   2008                  1931                  0.00
3                   1933                  1955                  0.00
4                   1967                  1954                  0.00
5                   1964                  1948                  0.00
6                   1972                  1954                  0.00
7                   1892                  2010                  0.00
8                   1891                  1986                  0.15
9                   1961                  1926                  0.00
10                  1961                  1986                  0.00

    average_precipitation  record_precipitation
0                    0.10                  5.91
1                    0.10                  1.53
3                    0.10                  2.63
4                    0.10                  1.65
5                    0.10                  1.95
6                    0.11                  2.37
7                    0.11                  1.87
8                    0.12                  3.71
9                    0.11                  2.45
10                   0.12                  3.10

In [31]:
#Question 7
## Add the row that you deleted before. Print the first 10 rows again.
df = pd.concat([df, ser], ignore_index = True)
print(df.iloc[0:10])

        date  actual_mean_temp  actual_min_temp  actual_max_temp  \
0   2014-7-1                81               70               91
1   2014-7-2                85               74               95
2   2014-7-4                75               64               86
3   2014-7-5                72               60               84
4   2014-7-6                74               61               87
5   2014-7-7                79               67               91
6   2014-7-8                83               72               94
7   2014-7-9                80               71               89
8  2014-7-10                78               71               85
9  2014-7-11                78               68               87

   average_min_temp  average_max_temp  record_min_temp  record_max_temp  \
0                67                89               56              104
1                68                89               56              101
2                68                89               55               99
3                68                89               57              100
4                68                89               57               99
5                68                89               55              100
6                68                89               58              101
7                68                89               57              101
8                68                89               53              101
9                68                89               55              100

   record_min_temp_year  record_max_temp_year  actual_precipitation  \
0                  1919                  2012                  0.00
1                  2008                  1931                  0.00
2                  1933                  1955                  0.00
3                  1967                  1954                  0.00
4                  1964                  1948                  0.00
5                  1972                  1954                  0.00
6                  1892                  2010                  0.00
7                  1891                  1986                  0.15
8                  1961                  1926                  0.00
9                  1961                  1986                  0.00

   average_precipitation  record_precipitation
0                   0.10                  5.91
1                   0.10                  1.53
2                   0.10                  2.63
3                   0.10                  1.65
4                   0.10                  1.95
5                   0.11                  2.37
6                   0.11                  1.87
7                   0.12                  3.71
8                   0.11                  2.45
9                   0.12                  3.10

In [32]:
#Question 8
#Update the actual_min_temp in the data row for date ‘2014-7-3’ to any value. Print the updated row.
#nm=df['date' == '2014-7-3'].index
for index, row in df.iterrows():
    if df.loc[index,'date'] == '2014-7-3':
       df.at[index,'actual_min_temp']=90
show=df[df.date=='2014-7-3']
print(show)

         date  actual_mean_temp  actual_min_temp  actual_max_temp  \
364  2014-7-3                82               90               93

     average_min_temp  average_max_temp  record_min_temp  record_max_temp  \
364                68                89               56               99

     record_min_temp_year  record_max_temp_year  actual_precipitation  \
364                  2010                  1931                  0.14

     average_precipitation  record_precipitation
364                   0.11                   2.5

In [33]:
#Question 9
# Print these 10 rows before and after the operation.
df.head(10)

,date,actual_mean_temp,actual_min_temp,actual_max_temp,average_min_temp,average_max_temp,record_min_temp,record_max_temp,record_min_temp_year,record_max_temp_year,actual_precipitation,average_precipitation,record_precipitation
0,2014-7-1,81,70,91,67,89,56,104,1919,2012,0.00,0.10,5.91
1,2014-7-2,85,74,95,68,89,56,101,2008,1931,0.00,0.10,1.53
2,2014-7-4,75,64,86,68,89,55,99,1933,1955,0.00,0.10,2.63
3,2014-7-5,72,60,84,68,89,57,100,1967,1954,0.00,0.10,1.65
4,2014-7-6,74,61,87,68,89,57,99,1964,1948,0.00,0.10,1.95
5,2014-7-7,79,67,91,68,89,55,100,1972,1954,0.00,0.11,2.37
6,2014-7-8,83,72,94,68,89,58,101,1892,2010,0.00,0.11,1.87
7,2014-7-9,80,71,89,68,89,57,101,1891,1986,0.15,0.12,3.71
8,2014-7-10,78,71,85,68,89,53,101,1961,1926,0.00,0.11,2.45
9,2014-7-11,78,68,87,68,89,55,100,1961,1986,0.00,0.12,3.10

In [34]:
#Question 9-----continue
##Add 5 to the ‘actual_mean_temp’ wherever the ‘actual_min_temp’ is odd. Do this only on the top 10 rows. Print these 10 rows before and after the operation.
for index, row in df.head(10).iterrows():
    if df.loc[index,'actual_min_temp']%2!=0:
       df.at[index,'actual_mean_temp']=df.at[index,'actual_mean_temp']+5
df.head(10)

,date,actual_mean_temp,actual_min_temp,actual_max_temp,average_min_temp,average_max_temp,record_min_temp,record_max_temp,record_min_temp_year,record_max_temp_year,actual_precipitation,average_precipitation,record_precipitation
0,2014-7-1,81,70,91,67,89,56,104,1919,2012,0.00,0.10,5.91
1,2014-7-2,85,74,95,68,89,56,101,2008,1931,0.00,0.10,1.53
2,2014-7-4,75,64,86,68,89,55,99,1933,1955,0.00,0.10,2.63
3,2014-7-5,72,60,84,68,89,57,100,1967,1954,0.00,0.10,1.65
4,2014-7-6,79,61,87,68,89,57,99,1964,1948,0.00,0.10,1.95
5,2014-7-7,84,67,91,68,89,55,100,1972,1954,0.00,0.11,2.37
6,2014-7-8,83,72,94,68,89,58,101,1892,2010,0.00,0.11,1.87
7,2014-7-9,85,71,89,68,89,57,101,1891,1986,0.15,0.12,3.71
8,2014-7-10,83,71,85,68,89,53,101,1961,1926,0.00,0.11,2.45
9,2014-7-11,78,68,87,68,89,55,100,1961,1986,0.00,0.12,3.10

In [35]:
#Question 10
#Print only those rows where the absolute difference between the ‘record_min_temp_year’ and ‘record_max_temp_year’ is less than 30.
for index, row in df.iterrows():  
    if abs(df.loc[index,'record_max_temp_year'] - df.loc[index,'record_min_temp_year']) < 30:
        print(row)

date                     2014-7-4
actual_mean_temp               75
actual_min_temp                64
actual_max_temp                86
average_min_temp               68
average_max_temp               89
record_min_temp                55
record_max_temp                99
record_min_temp_year         1933
record_max_temp_year         1955
actual_precipitation            0
average_precipitation         0.1
record_precipitation         2.63
Name: 2, dtype: object
date                     2014-7-5
actual_mean_temp               72
actual_min_temp                60
actual_max_temp                84
average_min_temp               68
average_max_temp               89
record_min_temp                57
record_max_temp               100
record_min_temp_year         1967
record_max_temp_year         1954
actual_precipitation            0
average_precipitation         0.1
record_precipitation         1.65
Name: 3, dtype: object
date                     2014-7-6
actual_mean_temp               79
actual_min_temp                61
actual_max_temp                87
average_min_temp               68
average_max_temp               89
record_min_temp                57
record_max_temp                99
record_min_temp_year         1964
record_max_temp_year         1948
actual_precipitation            0
average_precipitation         0.1
record_precipitation         1.95
Name: 4, dtype: object
date                     2014-7-7
actual_mean_temp               84
actual_min_temp                67
actual_max_temp                91
average_min_temp               68
average_max_temp               89
record_min_temp                55
record_max_temp               100
record_min_temp_year         1972
record_max_temp_year         1954
actual_precipitation            0
average_precipitation        0.11
record_precipitation         2.37
Name: 5, dtype: object
date                     2014-7-11
actual_mean_temp                78
actual_min_temp                 68
actual_max_temp                 87
average_min_temp                68
average_max_temp                89
record_min_temp                 55
record_max_temp                100
record_min_temp_year          1961
record_max_temp_year          1986
actual_precipitation             0
average_precipitation         0.12
record_precipitation           3.1
Name: 9, dtype: object
date                     2014-7-12
actual_mean_temp                79
actual_min_temp                 67
actual_max_temp                 91
average_min_temp                68
average_max_temp                89
record_min_temp                 59
record_max_temp                102
record_min_temp_year          1953
record_max_temp_year          1930
actual_precipitation             0
average_precipitation         0.11
record_precipitation          1.95
Name: 10, dtype: object
date                     2014-7-18
actual_mean_temp                77
actual_min_temp                 70
actual_max_temp                 83
average_min_temp                68
average_max_temp                89
record_min_temp                 62
record_max_temp                102
record_min_temp_year          1896
record_max_temp_year          1887
actual_precipitation             0
average_precipitation         0.12
record_precipitation          1.82
Name: 16, dtype: object
date                     2014-7-19
actual_mean_temp                70
actual_min_temp                 66
actual_max_temp                 74
average_min_temp                68
average_max_temp                89
record_min_temp                 60
record_max_temp                103
record_min_temp_year          2009
record_max_temp_year          1986
actual_precipitation          0.17
average_precipitation         0.12
record_precipitation           2.3
Name: 17, dtype: object
date                     2014-7-23
actual_mean_temp                80
actual_min_temp                 69
actual_max_temp                 90
average_min_temp                68
average_max_temp                89
record_min_temp                 56
record_max_temp                101
record_min_temp_year          2007
record_max_temp_year          1987
actual_precipitation             0
average_precipitation         0.13
record_precipitation          6.88
Name: 21, dtype: object
date                     2014-7-24
actual_mean_temp                80
actual_min_temp                 71
actual_max_temp                 89
average_min_temp                68
average_max_temp                89
record_min_temp                 59
record_max_temp                100
record_min_temp_year          1947
record_max_temp_year          1952
actual_precipitation          0.06
average_precipitation         0.12
record_precipitation          2.83
Name: 22, dtype: object
date                     2014-7-27
actual_mean_temp                80
actual_min_temp                 70
actual_max_temp                 90
average_min_temp                68
average_max_temp                89
record_min_temp                 57
record_max_temp                103
record_min_temp_year          1920
record_max_temp_year          1940
actual_precipitation          0.18
average_precipitation         0.13
record_precipitation          2.46
Name: 25, dtype: object
date                     2014-7-28
actual_mean_temp                79
actual_min_temp                 68
actual_max_temp                 90
average_min_temp                68
average_max_temp                89
record_min_temp                 54
record_max_temp                102
record_min_temp_year          1962
record_max_temp_year          1952
actual_precipitation          0.06
average_precipitation         0.13
record_precipitation          2.98
Name: 26, dtype: object
date                     2014-8-1
actual_mean_temp               68
actual_min_temp                65
actual_max_temp                70
average_min_temp               68
average_max_temp               89
record_min_temp                58
record_max_temp                98
record_min_temp_year         1966
record_max_temp_year         1957
actual_precipitation         2.39
average_precipitation        0.14
record_precipitation         2.39
Name: 30, dtype: object
date                     2014-8-3
actual_mean_temp               77
actual_min_temp                67
actual_max_temp                86
average_min_temp               68
average_max_temp               89
record_min_temp                60
record_max_temp                98
record_min_temp_year         1998
record_max_temp_year         2011
actual_precipitation            0
average_precipitation        0.15
record_precipitation         4.51
Name: 32, dtype: object
date                     2014-8-4
actual_mean_temp               78
actual_min_temp                69
actual_max_temp                87
average_min_temp               68
average_max_temp               89
record_min_temp                58
record_max_temp                98
record_min_temp_year         1912
record_max_temp_year         1935
actual_precipitation            0
average_precipitation        0.15
record_precipitation         2.59
Name: 33, dtype: object
date                     2014-8-8
actual_mean_temp               77
actual_min_temp                73
actual_max_temp                81
average_min_temp               68
average_max_temp               88
record_min_temp                55
record_max_temp               102
record_min_temp_year         2004
record_max_temp_year         2007
actual_precipitation            0
average_precipitation        0.13
record_precipitation         1.37
Name: 37, dtype: object
date                     2014-8-9
actual_mean_temp               76
actual_min_temp                68
actual_max_temp                84
average_min_temp               68
average_max_temp               88
record_min_temp                56
record_max_temp               104
record_min_temp_year         2002
record_max_temp_year         2007
actual_precipitation            0
average_precipitation        0.13
record_precipitation         1.26
Name: 38, dtype: object
date                     2014-8-13
actual_mean_temp                75
actual_min_temp                 65
actual_max_temp                 84
average_min_temp                68
average_max_temp                88
record_min_temp                 57
record_max_temp                102
record_min_temp_year          1979
record_max_temp_year          1956
actual_precipitation             0
average_precipitation         0.14
record_precipitation          1.27
Name: 42, dtype: object
date                     2014-8-18
actual_mean_temp                81
actual_min_temp                 71
actual_max_temp                 90
average_min_temp                67
average_max_temp                88
record_min_temp                 59
record_max_temp                101
record_min_temp_year          1976
record_max_temp_year          1988
actual_precipitation             0
average_precipitation         0.13
record_precipitation          1.76
Name: 47, dtype: object
date                     2014-8-19
actual_mean_temp                80
actual_min_temp                 70
actual_max_temp                 90
average_min_temp                67
average_max_temp                87
record_min_temp                 59
record_max_temp                100
record_min_temp_year          1981
record_max_temp_year          1988
actual_precipitation             0
average_precipitation         0.14
record_precipitation          1.96
Name: 48, dtype: object
date                     2014-8-20
actual_mean_temp                79
actual_min_temp                 67
actual_max_temp                 91
average_min_temp                67
average_max_temp                87
record_min_temp                 56
record_max_temp                103
record_min_temp_year          1918
record_max_temp_year          1925
actual_precipitation             0
average_precipitation         0.14
record_precipitation          1.84
Name: 49, dtype: object
date                     2014-8-21
actual_mean_temp                80
actual_min_temp                 67
actual_max_temp                 93
average_min_temp                67
average_max_temp                87
record_min_temp                 56
record_max_temp                103
record_min_temp_year          1998
record_max_temp_year          1983
actual_precipitation             0
average_precipitation         0.13
record_precipitation          2.22
Name: 50, dtype: object
date                     2014-8-25
actual_mean_temp                72
actual_min_temp                 60
actual_max_temp                 83
average_min_temp                66
average_max_temp                87
record_min_temp                 56
record_max_temp                 98
record_min_temp_year          1952
record_max_temp_year          1943
actual_precipitation             0
average_precipitation         0.14
record_precipitation          3.16
Name: 54, dtype: object
date                     2014-8-26
actual_mean_temp                72
actual_min_temp                 60
actual_max_temp                 84
average_min_temp                66
average_max_temp                87
record_min_temp                 55
record_max_temp                100
record_min_temp_year          1942
record_max_temp_year          1954
actual_precipitation             0
average_precipitation         0.14
record_precipitation          5.36
Name: 55, dtype: object
date                     2014-8-27
actual_mean_temp                72
actual_min_temp                 57
actual_max_temp                 87
average_min_temp                66
average_max_temp                86
record_min_temp                 55
record_max_temp                101
record_min_temp_year          1952
record_max_temp_year          1954
actual_precipitation             0
average_precipitation         0.13
record_precipitation          4.39
Name: 56, dtype: object
date                     2014-8-28
actual_mean_temp                77
actual_min_temp                 61
actual_max_temp                 92
average_min_temp                66
average_max_temp                86
record_min_temp                 55
record_max_temp                 98
record_min_temp_year          1905
record_max_temp_year          1924
actual_precipitation             0
average_precipitation         0.13
record_precipitation          4.64
Name: 57, dtype: object
date                     2014-8-31
actual_mean_temp                83
actual_min_temp                 74
actual_max_temp                 91
average_min_temp                65
average_max_temp                86
record_min_temp                 53
record_max_temp                 99
record_min_temp_year          1946
record_max_temp_year          1957
actual_precipitation          0.06
average_precipitation         0.12
record_precipitation           3.4
Name: 60, dtype: object
date                     2014-9-4
actual_mean_temp               77
actual_min_temp                69
actual_max_temp                85
average_min_temp               64
average_max_temp               85
record_min_temp                54
record_max_temp               100
record_min_temp_year         1952
record_max_temp_year         1925
actual_precipitation         0.82
average_precipitation        0.11
record_precipitation         1.15
Name: 64, dtype: object
date                     2014-9-5
actual_mean_temp               79
actual_min_temp                69
actual_max_temp                89
average_min_temp               64
average_max_temp               84
record_min_temp                54
record_max_temp               101
record_min_temp_year         1967
record_max_temp_year         1954
actual_precipitation         0.01
average_precipitation        0.11
record_precipitation         2.46
Name: 65, dtype: object
date                     2014-9-7
actual_mean_temp               79
actual_min_temp                70
actual_max_temp                88
average_min_temp               64
average_max_temp               84
record_min_temp                53
record_max_temp               100
record_min_temp_year         1924
record_max_temp_year         1925
actual_precipitation         0.09
average_precipitation        0.11
record_precipitation         2.38
Name: 67, dtype: object
date                     2014-9-12
actual_mean_temp                81
actual_min_temp                 72
actual_max_temp                 90
average_min_temp                62
average_max_temp                83
record_min_temp                 45
record_max_temp                 95
record_min_temp_year          1917
record_max_temp_year          1925
actual_precipitation          0.08
average_precipitation         0.09
record_precipitation          1.76
Name: 72, dtype: object
date                     2014-9-20
actual_mean_temp                71
actual_min_temp                 59
actual_max_temp                 82
average_min_temp                59
average_max_temp                80
record_min_temp                 45
record_max_temp                 98
record_min_temp_year          1929
record_max_temp_year          1925
actual_precipitation             0
average_precipitation         0.11
record_precipitation          2.82
Name: 80, dtype: object
date                     2014-9-21
actual_mean_temp                71
actual_min_temp                 57
actual_max_temp                 85
average_min_temp                59
average_max_temp                80
record_min_temp                 43
record_max_temp                 97
record_min_temp_year          1918
record_max_temp_year          1895
actual_precipitation             0
average_precipitation         0.11
record_precipitation          2.74
Name: 81, dtype: object
date                     2014-9-22
actual_mean_temp                69
actual_min_temp                 61
actual_max_temp                 76
average_min_temp                58
average_max_temp                79
record_min_temp                 43
record_max_temp                 98
record_min_temp_year          1918
record_max_temp_year          1895
actual_precipitation             0
average_precipitation          0.1
record_precipitation          2.92
Name: 82, dtype: object
date                     2014-9-26
actual_mean_temp                67
actual_min_temp                 62
actual_max_temp                 71
average_min_temp                57
average_max_temp                78
record_min_temp                 42
record_max_temp                 94
record_min_temp_year          1950
record_max_temp_year          1961
actual_precipitation             0
average_precipitation         0.11
record_precipitation          2.54
Name: 86, dtype: object
date                     2014-9-28
actual_mean_temp                68
actual_min_temp                 60
actual_max_temp                 76
average_min_temp                56
average_max_temp                77
record_min_temp                 41
record_max_temp                 93
record_min_temp_year          1947
record_max_temp_year          1954
actual_precipitation             0
average_precipitation         0.12
record_precipitation          3.38
Name: 88, dtype: object
date                     2014-9-29
actual_mean_temp                67
actual_min_temp                 64
actual_max_temp                 70
average_min_temp                55
average_max_temp                77
record_min_temp                 40
record_max_temp                 93
record_min_temp_year          1942
record_max_temp_year          1941
actual_precipitation          0.09
average_precipitation         0.11
record_precipitation          3.59
Name: 89, dtype: object
date                     2014-10-3
actual_mean_temp                70
actual_min_temp                 61
actual_max_temp                 79
average_min_temp                54
average_max_temp                76
record_min_temp                 36
record_max_temp                 91
record_min_temp_year          1974
record_max_temp_year          1954
actual_precipitation          0.03
average_precipitation         0.12
record_precipitation          2.15
Name: 93, dtype: object
date                     2014-10-4
actual_mean_temp                55
actual_min_temp                 43
actual_max_temp                 67
average_min_temp                53
average_max_temp                75
record_min_temp                 33
record_max_temp                 95
record_min_temp_year          1974
record_max_temp_year          1954
actual_precipitation             0
average_precipitation         0.12
record_precipitation          4.21
Name: 94, dtype: object
date                     2014-10-5
actual_mean_temp                52
actual_min_temp                 38
actual_max_temp                 65
average_min_temp                53
average_max_temp                75
record_min_temp                 38
record_max_temp                 97
record_min_temp_year          1974
record_max_temp_year          1954
actual_precipitation             0
average_precipitation         0.12
record_precipitation          1.16
Name: 95, dtype: object
date                     2014-10-6
actual_mean_temp                62
actual_min_temp                 47
actual_max_temp                 76
average_min_temp                52
average_max_temp                75
record_min_temp                 38
record_max_temp                 98
record_min_temp_year          1935
record_max_temp_year          1954
actual_precipitation             0
average_precipitation         0.12
record_precipitation          1.98
Name: 96, dtype: object
date                     2014-10-7
actual_mean_temp                67
actual_min_temp                 53
actual_max_temp                 80
average_min_temp                52
average_max_temp                74
record_min_temp                 34
record_max_temp                 91
record_min_temp_year          1935
record_max_temp_year          1951
actual_precipitation             0
average_precipitation         0.11
record_precipitation           2.7
Name: 97, dtype: object
date                     2014-10-9

In [36]:
print("Thanks!!")

Thanks!!